[2023-05-16T10:48:18.235+0530] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kafka_storm_connection.submit_topology_task manual__2023-05-16T05:16:57.799512+00:00 [queued]>
[2023-05-16T10:48:18.246+0530] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kafka_storm_connection.submit_topology_task manual__2023-05-16T05:16:57.799512+00:00 [queued]>
[2023-05-16T10:48:18.246+0530] {taskinstance.py:1331} INFO - Starting attempt 1 of 2
[2023-05-16T10:48:18.267+0530] {taskinstance.py:1350} INFO - Executing <Task(BashOperator): submit_topology_task> on 2023-05-16 05:16:57.799512+00:00
[2023-05-16T10:48:18.271+0530] {standard_task_runner.py:57} INFO - Started process 8109 to run task
[2023-05-16T10:48:18.277+0530] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'kafka_storm_connection', 'submit_topology_task', 'manual__2023-05-16T05:16:57.799512+00:00', '--job-id', '220', '--raw', '--subdir', 'DAGS_FOLDER/kafkastorm.py', '--cfg-path', '/tmp/tmpsxwzei55']
[2023-05-16T10:48:18.280+0530] {standard_task_runner.py:85} INFO - Job 220: Subtask submit_topology_task
[2023-05-16T10:48:18.342+0530] {task_command.py:410} INFO - Running <TaskInstance: kafka_storm_connection.submit_topology_task manual__2023-05-16T05:16:57.799512+00:00 [running]> on host nizam-HP-15-Notebook-PC
[2023-05-16T10:48:18.415+0530] {taskinstance.py:1568} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='kafka_storm_connection' AIRFLOW_CTX_TASK_ID='submit_topology_task' AIRFLOW_CTX_EXECUTION_DATE='2023-05-16T05:16:57.799512+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-05-16T05:16:57.799512+00:00'
[2023-05-16T10:48:18.417+0530] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-05-16T10:48:18.417+0530] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'storm jar /home/nizam/project/project/storm/project/Kafka-Storm/target/my_topology-1.0-jar-with-dependencies.jar org.apache.storm.flux.Flux --remote home/nizam/project/project/storm/project/Kafka-Storm/topologies/storm_configeration.yaml']
[2023-05-16T10:48:18.427+0530] {subprocess.py:86} INFO - Output:
[2023-05-16T10:48:27.729+0530] {subprocess.py:93} INFO - Running: /usr/lib/jvm/java-11-openjdk-amd64/bin/java -client -Ddaemon.name= -Dstorm.options= -Dstorm.home=/home/nizam/Downloads/apache-storm-1.2.3 -Dstorm.log.dir=/home/nizam/Downloads/apache-storm-1.2.3/logs -Djava.library.path=/usr/local/lib:/opt/local/lib:/usr/lib -Dstorm.conf.file= -cp /home/nizam/Downloads/apache-storm-1.2.3/*:/home/nizam/Downloads/apache-storm-1.2.3/lib/*:/home/nizam/Downloads/apache-storm-1.2.3/extlib/*:/home/nizam/project/project/storm/project/Kafka-Storm/target/my_topology-1.0-jar-with-dependencies.jar://home/nizam/Downloads/apache-storm-1.2.3/conf:/home/nizam/Downloads/apache-storm-1.2.3/bin -Dstorm.jar=/home/nizam/project/project/storm/project/Kafka-Storm/target/my_topology-1.0-jar-with-dependencies.jar -Dstorm.dependency.jars= -Dstorm.dependency.artifacts={} org.apache.storm.flux.Flux --remote home/nizam/project/project/storm/project/Kafka-Storm/topologies/storm_configeration.yaml
[2023-05-16T10:48:27.856+0530] {subprocess.py:93} INFO - Error: Could not find or load main class org.apache.storm.flux.Flux
[2023-05-16T10:48:27.856+0530] {subprocess.py:93} INFO - Caused by: java.lang.ClassNotFoundException: org.apache.storm.flux.Flux
[2023-05-16T10:48:27.861+0530] {subprocess.py:97} INFO - Command exited with return code 1
[2023-05-16T10:48:27.870+0530] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/nizam/env_airflow/lib/python3.10/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-05-16T10:48:27.874+0530] {taskinstance.py:1368} INFO - Marking task as UP_FOR_RETRY. dag_id=kafka_storm_connection, task_id=submit_topology_task, execution_date=20230516T051657, start_date=20230516T051818, end_date=20230516T051827
[2023-05-16T10:48:27.891+0530] {standard_task_runner.py:104} ERROR - Failed to execute job 220 for task submit_topology_task (Bash command failed. The command returned a non-zero exit code 1.; 8109)
[2023-05-16T10:48:27.912+0530] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-05-16T10:48:27.924+0530] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
