[2023-05-17T11:04:49.249+0530] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: storm_topology1.submit_topology manual__2023-05-17T05:29:28.231472+00:00 [queued]>
[2023-05-17T11:04:49.256+0530] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: storm_topology1.submit_topology manual__2023-05-17T05:29:28.231472+00:00 [queued]>
[2023-05-17T11:04:49.256+0530] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2023-05-17T11:04:49.274+0530] {taskinstance.py:1350} INFO - Executing <Task(BashOperator): submit_topology> on 2023-05-17 05:29:28.231472+00:00
[2023-05-17T11:04:49.279+0530] {standard_task_runner.py:57} INFO - Started process 8191 to run task
[2023-05-17T11:04:49.284+0530] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'storm_topology1', 'submit_topology', 'manual__2023-05-17T05:29:28.231472+00:00', '--job-id', '304', '--raw', '--subdir', 'DAGS_FOLDER/kafkastorm.py', '--cfg-path', '/tmp/tmp1t7h1415']
[2023-05-17T11:04:49.285+0530] {standard_task_runner.py:85} INFO - Job 304: Subtask submit_topology
[2023-05-17T11:04:49.332+0530] {task_command.py:410} INFO - Running <TaskInstance: storm_topology1.submit_topology manual__2023-05-17T05:29:28.231472+00:00 [running]> on host nizam-HP-15-Notebook-PC
[2023-05-17T11:04:49.405+0530] {taskinstance.py:1568} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='your_name' AIRFLOW_CTX_DAG_ID='storm_topology1' AIRFLOW_CTX_TASK_ID='submit_topology' AIRFLOW_CTX_EXECUTION_DATE='2023-05-17T05:29:28.231472+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-05-17T05:29:28.231472+00:00'
[2023-05-17T11:04:49.406+0530] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-05-17T11:04:49.407+0530] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /home/nizam/project/Kafka-Storm && sparse run --name first_topology']
[2023-05-17T11:04:49.417+0530] {subprocess.py:86} INFO - Output:
[2023-05-17T11:04:59.702+0530] {subprocess.py:93} INFO - Cleaning from prior builds...
[2023-05-17T11:05:01.548+0530] {subprocess.py:93} INFO - Creating topology Uber-JAR...
[2023-05-17T11:05:11.311+0530] {process_utils.py:131} INFO - Sending Signals.SIGTERM to group 8191. PIDs of all processes in the group: [8192, 8321, 8322, 8329, 8191]
[2023-05-17T11:05:11.312+0530] {process_utils.py:86} INFO - Sending the signal Signals.SIGTERM to group 8191
[2023-05-17T11:05:11.313+0530] {taskinstance.py:1540} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-05-17T11:05:11.313+0530] {subprocess.py:104} INFO - Sending SIGTERM signal to process group
[2023-05-17T11:05:11.333+0530] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/nizam/env_airflow/lib/python3.10/site-packages/airflow/operators/bash.py", line 201, in execute
    result = self.subprocess_hook.run_command(
  File "/home/nizam/env_airflow/lib/python3.10/site-packages/airflow/hooks/subprocess.py", line 91, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b""):
  File "/home/nizam/env_airflow/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1542, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2023-05-17T11:05:11.340+0530] {taskinstance.py:1368} INFO - Marking task as FAILED. dag_id=storm_topology1, task_id=submit_topology, execution_date=20230517T052928, start_date=20230517T053449, end_date=20230517T053511
[2023-05-17T11:05:11.361+0530] {standard_task_runner.py:104} ERROR - Failed to execute job 304 for task submit_topology (Task received SIGTERM signal; 8191)
[2023-05-17T11:05:11.367+0530] {process_utils.py:79} INFO - Process psutil.Process(pid=8329, status='terminated', started='11:05:01') (8329) terminated with exit code None
[2023-05-17T11:05:11.368+0530] {process_utils.py:79} INFO - Process psutil.Process(pid=8192, status='terminated', started='11:04:49') (8192) terminated with exit code None
[2023-05-17T11:05:11.368+0530] {process_utils.py:79} INFO - Process psutil.Process(pid=8322, status='terminated', started='11:05:01') (8322) terminated with exit code None
[2023-05-17T11:05:11.368+0530] {process_utils.py:79} INFO - Process psutil.Process(pid=8191, status='terminated', exitcode=1, started='11:04:49') (8191) terminated with exit code 1
[2023-05-17T11:05:11.369+0530] {process_utils.py:79} INFO - Process psutil.Process(pid=8321, status='terminated', started='11:05:01') (8321) terminated with exit code None
