[2023-05-16T12:07:33.265+0530] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mongodb_to_kafka_and_consumer.read_and_send_task manual__2023-05-16T06:37:29.106020+00:00 [queued]>
[2023-05-16T12:07:33.274+0530] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mongodb_to_kafka_and_consumer.read_and_send_task manual__2023-05-16T06:37:29.106020+00:00 [queued]>
[2023-05-16T12:07:33.274+0530] {taskinstance.py:1331} INFO - Starting attempt 1 of 2
[2023-05-16T12:07:33.292+0530] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): read_and_send_task> on 2023-05-16 06:37:29.106020+00:00
[2023-05-16T12:07:33.297+0530] {standard_task_runner.py:57} INFO - Started process 15503 to run task
[2023-05-16T12:07:33.301+0530] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'mongodb_to_kafka_and_consumer', 'read_and_send_task', 'manual__2023-05-16T06:37:29.106020+00:00', '--job-id', '250', '--raw', '--subdir', 'DAGS_FOLDER/test1.py', '--cfg-path', '/tmp/tmphs3ohlgj']
[2023-05-16T12:07:33.301+0530] {standard_task_runner.py:85} INFO - Job 250: Subtask read_and_send_task
[2023-05-16T12:07:33.355+0530] {task_command.py:410} INFO - Running <TaskInstance: mongodb_to_kafka_and_consumer.read_and_send_task manual__2023-05-16T06:37:29.106020+00:00 [running]> on host nizam-HP-15-Notebook-PC
[2023-05-16T12:07:33.436+0530] {taskinstance.py:1568} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='mongodb_to_kafka_and_consumer' AIRFLOW_CTX_TASK_ID='read_and_send_task' AIRFLOW_CTX_EXECUTION_DATE='2023-05-16T06:37:29.106020+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-05-16T06:37:29.106020+00:00'
[2023-05-16T12:07:33.510+0530] {conn.py:380} INFO - <BrokerConnection node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2023-05-16T12:07:33.510+0530] {conn.py:1205} INFO - Probing node bootstrap-0 broker version
[2023-05-16T12:07:33.511+0530] {conn.py:410} INFO - <BrokerConnection node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connection complete.
[2023-05-16T12:07:33.621+0530] {conn.py:1267} INFO - Broker version identified as 2.5.0
[2023-05-16T12:07:33.621+0530] {conn.py:1268} INFO - Set configuration api_version=(2, 5, 0) to skip auto check_version requests on startup
[2023-05-16T12:07:46.044+0530] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/nizam/env_airflow/lib/python3.10/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/nizam/env_airflow/lib/python3.10/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/nizam/airflow/dags/test1.py", line 55, in read_from_mongodb_and_send_to_kafka
    kwargs['ti'].success()
AttributeError: 'TaskInstance' object has no attribute 'success'
[2023-05-16T12:07:46.059+0530] {taskinstance.py:1368} INFO - Marking task as UP_FOR_RETRY. dag_id=mongodb_to_kafka_and_consumer, task_id=read_and_send_task, execution_date=20230516T063729, start_date=20230516T063733, end_date=20230516T063746
[2023-05-16T12:07:46.080+0530] {standard_task_runner.py:104} ERROR - Failed to execute job 250 for task read_and_send_task ('TaskInstance' object has no attribute 'success'; 15503)
[2023-05-16T12:07:46.109+0530] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-05-16T12:07:46.129+0530] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
