[2023-05-11T14:22:11.890+0530] {taskinstance.py:1115} INFO - Dependencies not met for <TaskInstance: test2.consume_from_kafka_task manual__2023-05-11T08:46:34.466519+00:00 [up_for_retry]>, dependency 'Not In Retry Period' FAILED: Task is not ready for retry yet but will be retried automatically. Current date is 2023-05-11T08:52:11.890586+00:00 and task will be retried at 2023-05-11T08:57:07.229567+00:00.
[2023-05-11T14:22:11.891+0530] {local_task_job_runner.py:161} INFO - Task is not able to be run
